#!/bin/bash

DIRS=("orders" "active_directory" "core" "ozone")

if [ -n "$VIRTUAL_ENV" ]; then
    dj_admin="$VIRTUAL_ENV/bin/django-admin.py"
else
    dj_admin="/usr/bin/django-admin.py"
fi

case "$1" in

    compile) ACTION="compilemessages"
             ;;

    *) ACTION="makemessages -l de"
       ;;

esac

for d in ${DIRS[@]}
do
    cd $d
    $dj_admin $ACTION
    cd ..
done

