#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

BASEDIR="/home/bbz/bbz-tools/ozone"
DAEMON="ozoned.py"
# PIDFILE must match PID_FILE from ozoned.py
PIDFILE="$BASEDIR/run/ozoned.pid"

if [ -f "$PIDFILE" ]; then
    PID=$(cat $PIDFILE)
else
    PID=""
fi

case "$1" in
    start)
        stat_busy "Starting $DAEMON"
        [ -z "$PID" ] && "$BASEDIR/$DAEMON" &>/dev/null
        if [ $? = 0 ]; then
            add_daemon $DAEMON
            stat_done
        else
            stat_fail
            exit 1
        fi
        ;;
    stop)
        stat_busy "Stopping $DAEMON"
        [ -n "$PID" ] && kill $PID &>/dev/null
        if [ $? = 0 ]; then
            rm_daemon $DAEMON
            stat_done
        else
            stat_fail
            exit 1
        fi
        ;;
    restart)
        $0 stop
        sleep 1
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
esac

